In [5]:
import pandas as pd
import numpy as np

pd.set_option("display.max_columns", None)
pd.set_option("display.float_format", "{:.2f}".format)

# CSV Exploration

## Patients

In [29]:
patients_df = pd.read_csv('../synthea_data/output/csv/patients.csv')
patients_df

,Id,BIRTHDATE,DEATHDATE,SSN,DRIVERS,PASSPORT,PREFIX,FIRST,MIDDLE,LAST,SUFFIX,MAIDEN,MARITAL,RACE,ETHNICITY,GENDER,BIRTHPLACE,ADDRESS,CITY,STATE,COUNTY,FIPS,ZIP,LAT,LON,HEALTHCARE_EXPENSES,HEALTHCARE_COVERAGE,INCOME
0,55cd6b62-0bea-10be-459c-7fd0e3dd1eeb,2020-02-15,NaN,999-51-7894,NaN,NaN,NaN,Larisa542,Twila243,Boyer713,NaN,NaN,NaN,white,nonhispanic,F,Randolph Massachusetts US,286 Berge Skyway,Webster,Massachusetts,Worcester County,25027.00,1570,42.10,-71.82,1466.96,15878.93,10638
1,18a9740d-5199-e6c3-fafb-346260c845e5,2013-01-02,NaN,999-98-6536,NaN,NaN,NaN,Sherice231,Coletta724,Hessel84,NaN,NaN,NaN,white,nonhispanic,F,Longmeadow Massachusetts US,193 Koelpin Ferry,Brockton,Massachusetts,Plymouth County,25023.00,2351,42.09,-71.07,2300.00,34936.18,25370
2,21d4aba4-1e33-f920-3cbc-2b94b30e6ede,2012-11-18,NaN,999-89-7670,NaN,NaN,NaN,Dyan186,Keiko299,Hettinger594,NaN,NaN,NaN,white,nonhispanic,F,Somerset Massachusetts US,958 Mante Crossing,Norton,Massachusetts,Bristol County,NaN,0,41.93,-71.21,30081.23,0.00,132363
3,5889f3ae-a719-5d59-7eaf-9bb3621ddd65,1958-11-06,2001-07-07,999-66-7393,S99916745,X49771156X,Mr.,Bob965,NaN,Jones311,NaN,NaN,D,other,nonhispanic,M,Riyadh Riyadh SA,459 Rohan Manor,Boston,Massachusetts,Suffolk County,25025.00,2120,42.31,-71.11,7408.44,97190.03,832
4,da44154c-64e9-9258-78bf-e9b9aef996f1,1986-03-02,NaN,999-34-3733,S99968996,X34910560X,Mr.,Ezequiel972,Chet188,Gulgowski816,NaN,NaN,M,white,nonhispanic,M,Chicopee Massachusetts US,275 Jones Ville Apt 42,Quincy,Massachusetts,Norfolk County,25021.00,2169,42.28,-71.04,112022.59,0.00,105542
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
114,1958a572-f9fa-ade5-1a8a-cf840ca66845,1921-03-31,2004-12-06,999-27-7336,S99970084,X42564492X,Mr.,Steven797,Gaston250,Stroman228,NaN,NaN,M,black,nonhispanic,M,Boston Massachusetts US,178 Gusikowski Fork Unit 77,Acton,Massachusetts,Middlesex County,NaN,0,42.45,-71.40,180844.92,404106.80,98501
115,0c59fb68-db4d-8682-6038-99487a6638d0,1921-03-31,1999-06-28,999-11-3291,S99943375,X35804279X,Mr.,Samuel331,Everette494,Langworth352,NaN,NaN,S,black,nonhispanic,M,Southampton Massachusetts US,657 Cummings Landing,Acton,Massachusetts,Middlesex County,NaN,0,42.46,-71.46,151540.21,3036910.94,98501
116,a7429b84-07bc-d8fb-7e31-22cef9e1d5e8,1921-03-31,1992-11-25,999-20-4209,S99958781,X21144329X,Mr.,Richie600,Frankie174,Okuneva707,NaN,NaN,M,black,nonhispanic,M,Webster Massachusetts US,295 Hudson Skyway,Acton,Massachusetts,Middlesex County,NaN,0,42.46,-71.48,180419.07,1204109.61,98501
117,a0e18afd-ee5a-c829-c267-46186d4de138,1921-03-31,1990-09-25,999-34-3798,S99910987,X09317759X,Mr.,Charley358,Aldo414,Murray856,NaN,NaN,D,black,nonhispanic,M,Boston Massachusetts US,833 Lynch Bypass,Acton,Massachusetts,Middlesex County,NaN,0,42.51,-71.43,247426.68,28218.37,98501
118,0468b94d-0d6d-492d-91ce-d28c254dba19,1921-03-31,NaN,999-16-8621,S99955304,X26490695X,Mr.,Gene733,NaN,Labadie908,NaN,NaN,D,black,nonhispanic,M,Medford Massachusetts US,654 Vandervort Lodge Unit 91,Acton,Massachusetts,Middlesex County,NaN,0,42.47,-71.40,193745.85,647453.87,98501

In [30]:
patients_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 119 entries, 0 to 118
Data columns (total 28 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Id                   119 non-null    object
 1   BIRTHDATE            119 non-null    object
 2   DEATHDATE            19 non-null     object
 3   SSN                  119 non-null    object
 4   DRIVERS              96 non-null     object
 5   PASSPORT             89 non-null     object
 6   PREFIX               92 non-null     object
 7   FIRST                119 non-null    object
 8   MIDDLE               101 non-null    object
 9   LAST                 119 non-null    object
 10  SUFFIX               2 non-null      object
 11  MAIDEN               25 non-null     object
 12  MARITAL              70 non-null     object
 13  RACE                 119 non-null    object
 14  ETHNICITY            119 non-null    object
 15  GENDER               119 non-null    object
 16  BIRTHPLACE           119 non-null    object
 17  ADDRESS              119 non-null    object
 18  CITY                 119 non-null    object
 19  STATE                119 non-null    object
 20  COUNTY               119 non-null    object
 21  FIPS                 77 non-null     float64
 22  ZIP                  119 non-null    int64
 23  LAT                  119 non-null    float64
 24  LON                  119 non-null    float64
 25  HEALTHCARE_EXPENSES  119 non-null    float64
 26  HEALTHCARE_COVERAGE  119 non-null    float64
 27  INCOME               119 non-null    int64
dtypes: float64(5), int64(2), object(21)
memory usage: 26.2+ KB

## Allergies

In [7]:
allergies_df = pd.read_csv('../synthea_data/output/csv/allergies.csv')
allergies_df

,START,STOP,PATIENT,ENCOUNTER,CODE,SYSTEM,DESCRIPTION,TYPE,CATEGORY,REACTION1,DESCRIPTION1,SEVERITY1,REACTION2,DESCRIPTION2,SEVERITY2
0,1987-04-22,NaN,277e37e0-e456-7fda-e471-0451fc5d0c86,277e37e0-e456-7fda-39cc-94e5ffd5caf0,609328004,SNOMED-CT,Allergic disposition (finding),allergy,environment,NaN,NaN,NaN,NaN,NaN,NaN
1,1987-04-22,NaN,277e37e0-e456-7fda-e471-0451fc5d0c86,277e37e0-e456-7fda-39cc-94e5ffd5caf0,288328004,SNOMED-CT,Bee venom (substance),allergy,environment,NaN,NaN,NaN,NaN,NaN,NaN
2,1987-04-22,NaN,277e37e0-e456-7fda-e471-0451fc5d0c86,277e37e0-e456-7fda-39cc-94e5ffd5caf0,84489001,SNOMED-CT,Mold (organism),allergy,environment,NaN,NaN,NaN,NaN,NaN,NaN
3,1987-04-22,NaN,277e37e0-e456-7fda-e471-0451fc5d0c86,277e37e0-e456-7fda-39cc-94e5ffd5caf0,260147004,SNOMED-CT,House dust mite (organism),allergy,environment,NaN,NaN,NaN,NaN,NaN,NaN
4,1987-04-22,NaN,277e37e0-e456-7fda-e471-0451fc5d0c86,277e37e0-e456-7fda-39cc-94e5ffd5caf0,264287008,SNOMED-CT,Animal dander (substance),allergy,environment,878820003.00,Rhinoconjunctivitis (disorder),MODERATE,247472004.00,Wheal (finding),MILD
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
130,1991-12-22,NaN,e66560a6-5282-fe47-7463-a05fd72d57c7,e66560a6-5282-fe47-3a47-9dad7d4c235c,762952008,SNOMED-CT,Peanut (substance),allergy,food,402387002.00,Allergic angioedema (disorder),MODERATE,300359004.00,Finding of vomiting (finding),MILD
131,1991-06-26,NaN,e83be37d-e309-3fbc-5fba-0df307678193,e83be37d-e309-3fbc-9596-4a348e9e5efa,609328004,SNOMED-CT,Allergic disposition (finding),allergy,environment,NaN,NaN,NaN,NaN,NaN,NaN
132,1991-06-26,NaN,e83be37d-e309-3fbc-5fba-0df307678193,e83be37d-e309-3fbc-9596-4a348e9e5efa,111088007,SNOMED-CT,Latex (substance),allergy,environment,247472004.00,Wheal (finding),MILD,NaN,NaN,NaN
133,1978-01-10,NaN,376bdbc6-7276-17c0-fca6-8aa7b2b02dbf,376bdbc6-7276-17c0-7e3e-cfee3f387c0e,609328004,SNOMED-CT,Allergic disposition (finding),allergy,environment,NaN,NaN,NaN,NaN,NaN,NaN
134,1978-01-10,NaN,376bdbc6-7276-17c0-fca6-8aa7b2b02dbf,376bdbc6-7276-17c0-7e3e-cfee3f387c0e,782576004,SNOMED-CT,Tree pollen (substance),allergy,environment,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
allergies_df['PATIENT'].nunique()

24

In [26]:
allergies_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 135 entries, 0 to 134
Data columns (total 15 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   START         135 non-null    object
 1   STOP          0 non-null      float64
 2   PATIENT       135 non-null    object
 3   ENCOUNTER     135 non-null    object
 4   CODE          135 non-null    int64
 5   SYSTEM        135 non-null    object
 6   DESCRIPTION   135 non-null    object
 7   TYPE          135 non-null    object
 8   CATEGORY      135 non-null    object
 9   REACTION1     55 non-null     float64
 10  DESCRIPTION1  55 non-null     object
 11  SEVERITY1     55 non-null     object
 12  REACTION2     34 non-null     float64
 13  DESCRIPTION2  34 non-null     object
 14  SEVERITY2     34 non-null     object
dtypes: float64(3), int64(1), object(11)
memory usage: 15.9+ KB

In [27]:
# drop STOP column because everything is null?
allergies_df.drop(columns=['STOP'], inplace = True)

In [28]:
allergies_df[allergies_df['PATIENT'] == '277e37e0-e456-7fda-e471-0451fc5d0c86']

,START,PATIENT,ENCOUNTER,CODE,SYSTEM,DESCRIPTION,TYPE,CATEGORY,REACTION1,DESCRIPTION1,SEVERITY1,REACTION2,DESCRIPTION2,SEVERITY2
0,1987-04-22,277e37e0-e456-7fda-e471-0451fc5d0c86,277e37e0-e456-7fda-39cc-94e5ffd5caf0,609328004,SNOMED-CT,Allergic disposition (finding),allergy,environment,NaN,NaN,NaN,NaN,NaN,NaN
1,1987-04-22,277e37e0-e456-7fda-e471-0451fc5d0c86,277e37e0-e456-7fda-39cc-94e5ffd5caf0,288328004,SNOMED-CT,Bee venom (substance),allergy,environment,NaN,NaN,NaN,NaN,NaN,NaN
2,1987-04-22,277e37e0-e456-7fda-e471-0451fc5d0c86,277e37e0-e456-7fda-39cc-94e5ffd5caf0,84489001,SNOMED-CT,Mold (organism),allergy,environment,NaN,NaN,NaN,NaN,NaN,NaN
3,1987-04-22,277e37e0-e456-7fda-e471-0451fc5d0c86,277e37e0-e456-7fda-39cc-94e5ffd5caf0,260147004,SNOMED-CT,House dust mite (organism),allergy,environment,NaN,NaN,NaN,NaN,NaN,NaN
4,1987-04-22,277e37e0-e456-7fda-e471-0451fc5d0c86,277e37e0-e456-7fda-39cc-94e5ffd5caf0,264287008,SNOMED-CT,Animal dander (substance),allergy,environment,878820003.00,Rhinoconjunctivitis (disorder),MODERATE,247472004.00,Wheal (finding),MILD
5,1987-04-22,277e37e0-e456-7fda-e471-0451fc5d0c86,277e37e0-e456-7fda-39cc-94e5ffd5caf0,256277009,SNOMED-CT,Grass pollen (substance),allergy,environment,NaN,NaN,NaN,NaN,NaN,NaN
6,1987-04-22,277e37e0-e456-7fda-e471-0451fc5d0c86,277e37e0-e456-7fda-39cc-94e5ffd5caf0,782576004,SNOMED-CT,Tree pollen (substance),allergy,environment,NaN,NaN,NaN,NaN,NaN,NaN
7,1987-04-22,277e37e0-e456-7fda-e471-0451fc5d0c86,277e37e0-e456-7fda-39cc-94e5ffd5caf0,442571000124108,SNOMED-CT,Tree nut (substance),allergy,food,39579001.00,Anaphylaxis (disorder),SEVERE,247472004.00,Wheal (finding),MODERATE

In [10]:
allergies_df.describe()

       STOP               CODE    REACTION1    REACTION2
count  0.00             135.00        55.00        34.00
mean    NaN  13113577822141.55 316287476.40 245605239.26
std     NaN  75323231881610.97 293750952.39 145777557.05
min     NaN            1191.00  21626009.00  49727002.00
25%     NaN       111088007.00  56021005.00 247472004.00
50%     NaN       264287008.00 267036007.00 269421505.00
75%     NaN       609328004.00 402387002.00 271807003.00
max     NaN 442571000124108.00 878820003.00 878820003.00

In [12]:
allergies_df['STOP'].unique()

array([nan])

## Careplans

In [14]:
careplans_df = pd.read_csv('../synthea_data/output/csv/careplans.csv')
careplans_df

,Id,START,STOP,PATIENT,ENCOUNTER,CODE,DESCRIPTION,REASONCODE,REASONDESCRIPTION
0,55cd6b62-0bea-10be-190a-8eb3e9fb8cee,2023-02-10,2023-03-21,55cd6b62-0bea-10be-459c-7fd0e3dd1eeb,55cd6b62-0bea-10be-72e6-4d167b76016a,385691007,Fracture care (regime/therapy),58150001.00,Fracture of clavicle (disorder)
1,5889f3ae-a719-5d59-3c87-a53e408ae155,1965-10-28,NaN,5889f3ae-a719-5d59-7eaf-9bb3621ddd65,5889f3ae-a719-5d59-e6c2-a0bee0d997b1,718361005,Weight management program (regime/therapy),NaN,NaN
2,5889f3ae-a719-5d59-2011-82f39527c587,1990-08-30,1993-01-21,5889f3ae-a719-5d59-7eaf-9bb3621ddd65,5889f3ae-a719-5d59-fa47-659f81bc3d5b,53950000,Respiratory therapy (procedure),NaN,NaN
3,da44154c-64e9-9258-f63d-b8f6d609136a,2008-05-04,NaN,da44154c-64e9-9258-78bf-e9b9aef996f1,da44154c-64e9-9258-91fd-636f64dfd131,735985000,Diabetes self management plan (record artifact),714628002.00,Prediabetes (finding)
4,da44154c-64e9-9258-c30f-91d4413995a9,2017-05-14,NaN,da44154c-64e9-9258-78bf-e9b9aef996f1,da44154c-64e9-9258-5c45-95c8734639c3,443402002,Lifestyle education regarding hypertension (pr...,59621000.00,Essential hypertension (disorder)
...,...,...,...,...,...,...,...,...,...
393,0468b94d-0d6d-492d-ebb7-33365c1ae9d3,2005-03-12,NaN,0468b94d-0d6d-492d-91ce-d28c254dba19,0468b94d-0d6d-492d-cc26-97557cc5b08c,734163000,Care plan (record artifact),60573004.00,Aortic valve stenosis (disorder)
394,0468b94d-0d6d-492d-f3c8-9fbb0ceb93a9,2020-06-06,2020-06-26,0468b94d-0d6d-492d-91ce-d28c254dba19,0468b94d-0d6d-492d-2569-43de4e3e4653,225358003,Wound care (regime/therapy),283385000.00,Laceration of thigh (disorder)
395,0468b94d-0d6d-492d-d2e7-46436405d97d,2022-04-21,2022-06-08,0468b94d-0d6d-492d-91ce-d28c254dba19,0468b94d-0d6d-492d-8af9-d845fd2a7628,385691007,Fracture care (regime/therapy),263102004.00,Fracture subluxation of wrist (disorder)
396,0468b94d-0d6d-492d-3723-9f5720b62fd6,2023-10-17,2023-11-06,0468b94d-0d6d-492d-91ce-d28c254dba19,0468b94d-0d6d-492d-f3d9-3478f1efa91e,53950000,Respiratory therapy (procedure),NaN,NaN
397,0468b94d-0d6d-492d-4c8e-3c30417dadb9,2025-03-30,NaN,0468b94d-0d6d-492d-91ce-d28c254dba19,0468b94d-0d6d-492d-cfe5-1b1774c826e3,736690008,Dialysis care plan (record artifact),NaN,NaN

In [16]:
careplans_df['PATIENT'].nunique()

105

In [21]:
careplans_df.groupby(['PATIENT']).count()['Id'].sort_values(ascending=False)

PATIENT
1958a572-f9fa-ade5-1a8a-cf840ca66845    11
29447d58-9b67-25c4-9491-e62621872d94    11
22c6ab5f-3515-4688-b62b-48dd234ad17c     9
77eca2c5-5909-f329-3b81-8753da4734e3     9
60fcf42f-7e23-9fc2-2ba9-d0bb0145cabf     8
                                        ..
cc153a26-c50c-8b2b-2e3a-1f4a19d56ff0     1
d94bbf58-de65-ef32-6cb4-34f91af6d082     1
ba55a586-76ca-1ea6-910c-8d37394937e5     1
f14dba51-a429-0d87-64ad-234fe63aa4a3     1
eead346d-45c4-ecbf-3931-568ba7fe1347     1
Name: Id, Length: 105, dtype: int64

In [23]:
careplans_df[careplans_df['PATIENT'] == '1958a572-f9fa-ade5-1a8a-cf840ca66845']

,Id,START,STOP,PATIENT,ENCOUNTER,CODE,DESCRIPTION,REASONCODE,REASONDESCRIPTION
368,1958a572-f9fa-ade5-f280-8166ac5f6104,1924-12-07,NaN,1958a572-f9fa-ade5-1a8a-cf840ca66845,1958a572-f9fa-ade5-b179-487dbd0cfce5,699728000,Asthma self management (regime/therapy),233678006.00,Childhood asthma (disorder)
369,1958a572-f9fa-ade5-1ef5-69c8452daa02,1957-09-05,NaN,1958a572-f9fa-ade5-1a8a-cf840ca66845,1958a572-f9fa-ade5-1b9e-a23bdb2faf16,735985000,Diabetes self management plan (record artifact),714628002.00,Prediabetes (finding)
370,1958a572-f9fa-ade5-9864-ce81b3b44eb7,1961-04-03,NaN,1958a572-f9fa-ade5-1a8a-cf840ca66845,1958a572-f9fa-ade5-5c67-1dffeef90990,734163000,Care plan (record artifact),78275009.00,Obstructive sleep apnea syndrome (disorder)
371,1958a572-f9fa-ade5-deb3-0d72d1a4aeb6,1970-04-28,NaN,1958a572-f9fa-ade5-1a8a-cf840ca66845,1958a572-f9fa-ade5-d907-fef029a10413,408869004,Musculoskeletal care (regime/therapy),239872002.00,Osteoarthritis of hip (disorder)
372,1958a572-f9fa-ade5-8de7-eb3eee04dbac,1989-11-01,NaN,1958a572-f9fa-ade5-1a8a-cf840ca66845,1958a572-f9fa-ade5-13d4-e647702b2d0c,736372004,Discharge care plan (record artifact),NaN,NaN
373,1958a572-f9fa-ade5-a692-f645cfbd8ba6,1998-01-29,NaN,1958a572-f9fa-ade5-1a8a-cf840ca66845,1958a572-f9fa-ade5-3615-1f2cb15bc0cd,736285004,Hyperlipidemia clinical management plan (recor...,55822004.00,Hyperlipidemia (disorder)
374,1958a572-f9fa-ade5-3a94-2f321e07b241,2002-05-16,NaN,1958a572-f9fa-ade5-1a8a-cf840ca66845,1958a572-f9fa-ade5-a73e-b8f00a4bc9dd,735984001,Heart failure self management plan (record art...,88805009.00,Chronic congestive heart failure (disorder)
375,1958a572-f9fa-ade5-da21-475b92999a42,2002-11-12,2002-11-16,1958a572-f9fa-ade5-1a8a-cf840ca66845,1958a572-f9fa-ade5-9de2-43ceaa437d62,736353004,Inpatient care plan (record artifact),88805009.00,Chronic congestive heart failure (disorder)
376,1958a572-f9fa-ade5-4f21-a36227aa2d4b,2003-11-04,2003-11-17,1958a572-f9fa-ade5-1a8a-cf840ca66845,1958a572-f9fa-ade5-a86e-77a75683cc13,53950000,Respiratory therapy (procedure),NaN,NaN
377,1958a572-f9fa-ade5-88fe-39241c3733b5,2004-06-03,2004-06-06,1958a572-f9fa-ade5-1a8a-cf840ca66845,1958a572-f9fa-ade5-e3cd-4e5fdba2e9a5,736353004,Inpatient care plan (record artifact),88805009.00,Chronic congestive heart failure (disorder)
378,1958a572-f9fa-ade5-d7dc-801bf3e85cfd,2004-12-03,NaN,1958a572-f9fa-ade5-1a8a-cf840ca66845,1958a572-f9fa-ade5-2218-19bf2c7f297d,736353004,Inpatient care plan (record artifact),88805009.00,Chronic congestive heart failure (disorder)

## Claims Transactions

In [24]:
claims_txns_df = pd.read_csv('../synthea_data/output/csv/claims_transactions.csv')
claims_txns_df

,ID,CLAIMID,CHARGEID,PATIENTID,TYPE,AMOUNT,METHOD,FROMDATE,TODATE,PLACEOFSERVICE,PROCEDURECODE,MODIFIER1,MODIFIER2,DIAGNOSISREF1,DIAGNOSISREF2,DIAGNOSISREF3,DIAGNOSISREF4,UNITS,DEPARTMENTID,NOTES,UNITAMOUNT,TRANSFEROUTID,TRANSFERTYPE,PAYMENTS,ADJUSTMENTS,TRANSFERS,OUTSTANDING,APPOINTMENTID,LINENOTE,PATIENTINSURANCEID,FEESCHEDULEID,PROVIDERID,SUPERVISINGPROVIDERID
0,44d0676e-a725-6c90-620d-ae1bfc3eb797,55cd6b62-0bea-10be-3816-41f318f467ad,0,55cd6b62-0bea-10be-459c-7fd0e3dd1eeb,CHARGE,136.80,NaN,2020-02-15T01:09:24Z,2020-02-15T01:24:24Z,a6fb79e7-4abb-3a68-b62d-e501427fdca4,410620009,NaN,NaN,1,NaN,NaN,NaN,1,10,Well child visit (procedure),136.80,NaN,1,0.00,0.00,NaN,0.00,55cd6b62-0bea-10be-dbe3-109bb53c899a,NaN,55cd6b62-0bea-10be-6842-5bdd13a63efc,1,bfb390bf-2bee-36ed-b738-ce93aa40a303,bfb390bf-2bee-36ed-b738-ce93aa40a303
1,89a0cede-5a4a-d920-c41b-5c38047d6f2e,55cd6b62-0bea-10be-3816-41f318f467ad,1,55cd6b62-0bea-10be-459c-7fd0e3dd1eeb,PAYMENT,NaN,ECHECK,2020-02-15T01:09:24Z,2020-02-15T01:24:24Z,a6fb79e7-4abb-3a68-b62d-e501427fdca4,410620009,NaN,NaN,1,NaN,NaN,NaN,1,10,Well child visit (procedure),0.00,NaN,NaN,36.80,0.00,NaN,100.00,55cd6b62-0bea-10be-dbe3-109bb53c899a,NaN,55cd6b62-0bea-10be-6842-5bdd13a63efc,1,bfb390bf-2bee-36ed-b738-ce93aa40a303,bfb390bf-2bee-36ed-b738-ce93aa40a303
2,13419dbf-b495-b241-8836-b87308fade5d,55cd6b62-0bea-10be-3816-41f318f467ad,2,55cd6b62-0bea-10be-459c-7fd0e3dd1eeb,TRANSFEROUT,NaN,NaN,2020-02-15T01:09:24Z,2020-02-15T01:24:24Z,a6fb79e7-4abb-3a68-b62d-e501427fdca4,410620009,NaN,NaN,1,NaN,NaN,NaN,1,10,Well child visit (procedure),0.00,NaN,NaN,0.00,0.00,100.00,100.00,55cd6b62-0bea-10be-dbe3-109bb53c899a,NaN,55cd6b62-0bea-10be-6842-5bdd13a63efc,1,bfb390bf-2bee-36ed-b738-ce93aa40a303,bfb390bf-2bee-36ed-b738-ce93aa40a303
3,26833b82-692b-6482-106d-70e911f5bcbb,55cd6b62-0bea-10be-3816-41f318f467ad,3,55cd6b62-0bea-10be-459c-7fd0e3dd1eeb,TRANSFERIN,100.00,NaN,2020-02-15T01:09:24Z,2020-02-15T01:24:24Z,a6fb79e7-4abb-3a68-b62d-e501427fdca4,410620009,NaN,NaN,1,NaN,NaN,NaN,1,10,Well child visit (procedure),0.00,2.00,p,0.00,0.00,100.00,100.00,55cd6b62-0bea-10be-dbe3-109bb53c899a,NaN,55cd6b62-0bea-10be-6842-5bdd13a63efc,1,bfb390bf-2bee-36ed-b738-ce93aa40a303,bfb390bf-2bee-36ed-b738-ce93aa40a303
4,4d067708-d256-c904-20da-e1de23eb7976,55cd6b62-0bea-10be-3816-41f318f467ad,4,55cd6b62-0bea-10be-459c-7fd0e3dd1eeb,PAYMENT,NaN,CHECK,2020-02-15T01:09:24Z,2020-02-15T01:24:24Z,a6fb79e7-4abb-3a68-b62d-e501427fdca4,410620009,NaN,NaN,1,NaN,NaN,NaN,1,10,Well child visit (procedure),0.00,NaN,NaN,100.00,0.00,NaN,0.00,55cd6b62-0bea-10be-dbe3-109bb53c899a,NaN,55cd6b62-0bea-10be-6842-5bdd13a63efc,1,bfb390bf-2bee-36ed-b738-ce93aa40a303,bfb390bf-2bee-36ed-b738-ce93aa40a303
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
99429,8eb8349e-efbf-2634-01a1-3ef2ac633794,0468b94d-0d6d-492d-8076-9247453f1232,128594,0468b94d-0d6d-492d-91ce-d28c254dba19,CHARGE,512.03,NaN,2026-07-29T00:42:12Z,2026-07-29T04:09:12Z,5fcff9db-16e4-3e56-aa78-abbc16338097,265764009,NaN,NaN,1,NaN,NaN,NaN,1,1,Renal dialysis (procedure),512.03,NaN,1,0.00,0.00,NaN,0.00,0468b94d-0d6d-492d-3c9f-ce3476d2a824,NaN,0468b94d-0d6d-492d-9bb1-94aff378884c,1,1a4726ce-b419-38c6-858e-cb9b7d14ca48,1a4726ce-b419-38c6-858e-cb9b7d14ca48
99430,1d70693d-df7e-4c99-0342-7de558c66f58,0468b94d-0d6d-492d-8076-9247453f1232,128595,0468b94d-0d6d-492d-91ce-d28c254dba19,PAYMENT,NaN,ECHECK,2026-07-29T00:42:12Z,2026-07-29T04:09:12Z,5fcff9db-16e4-3e56-aa78-abbc16338097,265764009,NaN,NaN,1,NaN,NaN,NaN,1,1,Renal dialysis (procedure),0.00,NaN,NaN,409.62,0.00,NaN,102.41,0468b94d-0d6d-492d-3c9f-ce3476d2a824,NaN,0468b94d-0d6d-492d-9bb1-94aff378884c,1,1a4726ce-b419-38c6-858e-cb9b7d14ca48,1a4726ce-b419-38c6-858e-cb9b7d14ca48
99431,3ae0d27b-befc-99f2-0684-fbcab18cdf70,0468b94d-0d6d-492d-8076-9247453f1232,128596,0468b94d-0d6d-492d-91ce-d28c254dba19,TRANSFEROUT,NaN,NaN,2026-07-29T00:42:12Z,2026-07-29T04:09:12Z,5fcff9db-16e4-3e56-aa78-abbc16338097,265764009,NaN,NaN,1,NaN,NaN,NaN,1,1,Renal dialysis (procedure),0.00,NaN,NaN,0.00,0.00,102.41,102.41,0468b94d-0d6d-492d-3c9f-ce3476d2a824,NaN,0468b94d-0d6d-492d-9bb1-94aff378884c,1,1a4726ce-b419-38c6-858e-cb9b7d14ca48,1a4726ce-b419-38c6-858e-cb9b7d14ca48
99432,75c1a4f7-7df9-3414-0d09-f7956319bf10,0468b94d-0d6d-492d-8076-9247453f1232,128597,0468b94d-0d6d-492d-91ce-d28c254dba19,TRANSFERIN,102.41,NaN,2026-07-29T00:42:12Z,2026-07-29T04:09:12Z,5fcff9db-16e4-3e56-aa78-abbc16338097,265764009,NaN,NaN,1,NaN,NaN,NaN,1,1,Renal dialysis (procedure),0.00,128596.00,2,0.00,0.00,102.41,102.41,0468b94d-0d6d-492d-3c9f-ce3476d2a824,NaN,0468b94d-0d6d-492d-9bb1-94aff378884c,1,1a4726ce-b419-38c6-858e-cb9b7d14ca48,1a4726ce-b419-38c6-858e-cb9b7d14ca48
99433,eb8349ee-fbf2-6b28-1a13-ef2ac6338120,0468b94d-0d6d-492d-8076-9247453f1232,128598,0468b94d-0d6d-492d-91ce-d28c254dba19,PAYMENT,NaN,ECHECK,2026-07-29T00:42:12Z,2026-07-29T04:09:12Z,5fcff9db-16e4-3e56-aa78-abbc16338097,265764009,NaN,NaN,1,NaN,NaN,NaN,1,1,Renal dialysis (procedure),0.00,NaN,NaN,102.41,0.00,NaN,0.00,0468b94d-0d6d-492d-3c9f-ce3476d2a824,NaN,0468b94d-0d6d-492d-9bb1-94aff378884c,1,1a4726ce-b419-38c6-858e-cb9b7d14ca48,1a4726ce-b419-38c6-858e-cb9b7d14ca48